version: "2"
services:
  db:
    ports:
      - "5432:5432"
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
